"""
Encryption service for sensitive data (UDP passwords)
Uses Fernet (symmetric encryption)
"""
import os
import sys
from cryptography.fernet import Fernet
from dotenv import load_dotenv
from utils.logging import log
from utils.config_loader import get_config_value

# Load environment variables from .env file
# Check Docker data directory first, then current directory
from pathlib import Path
docker_env = Path('/app/data/.env')
if docker_env.exists():
    load_dotenv(docker_env)
else:
    load_dotenv()


def get_encryption_key():
    """
    Get encryption key from environment
    
    Returns:
        bytes: Encryption key
        
    Raises:
        SystemExit: If ENCRYPTION_KEY not set
    """
    encryption_key_env = get_config_value('security', 'security.keys.encryption_key_env', default='ENCRYPTION_KEY')
    key = os.getenv(encryption_key_env, "")
    
    if not key:
        log("\n" + "="*60)
        log("  [SECURITY ERROR] ENCRYPTION_KEY not set!")
        log("="*60)
        log("\nRun: python utils/init_security.py")
        log("\nThis will generate ENCRYPTION_KEY\n")
        sys.exit(1)

    # Key is already Fernet-compatible (generated by Fernet.generate_key())
    return key.encode()


# Initialize Fernet cipher
_cipher = None


def get_cipher():
    """
    Get Fernet cipher instance (singleton)
    
    Returns:
        Fernet: Cipher instance
    """
    global _cipher
    if _cipher is None:
        _cipher = Fernet(get_encryption_key())
    return _cipher


def encrypt_password(password: str) -> str:
    """
    Encrypt password for storage
    
    Args:
        password: Plain text password
        
    Returns:
        str: Encrypted password (base64 string)
    """
    if not password:
        return ""

    cipher = get_cipher()
    encrypted = cipher.encrypt(password.encode())
    return encrypted.decode()


def decrypt_password(encrypted_password: str) -> str:
    """
    Decrypt password from storage
    
    Args:
        encrypted_password: Encrypted password string
        
    Returns:
        str: Plain text password
    """
    if not encrypted_password:
        return ""

    # Попытка расшифровать
    try:
        cipher = get_cipher()
        decrypted = cipher.decrypt(encrypted_password.encode())
        return decrypted.decode()
    except Exception:
        pass  # Первая попытка не удалась

    # Проверка: это plain text пароль для обратной совместимости?
    # Plain text пароль НЕ должен начинаться с "gAAAAA" (Fernet prefix)
    if encrypted_password.startswith('gAAAAA'):
        # Это явно Fernet-зашифрованные данные, но расшифровка не удалась
        log(f"[ERROR] Failed to decrypt password - corrupted or wrong key", level="ERROR")
        return ""  # Возвращаем пустую строку при ошибке

    # Это plain text пароль (обратная совместимость)
    log(f"[INFO] Using backward compatibility mode for server credentials")
    return encrypted_password

