"""
Encryption module for sensitive data (UDP passwords)
Uses Fernet (symmetric encryption)
"""
import os
import sys
from cryptography.fernet import Fernet
import base64
import hashlib
from dotenv import load_dotenv
from logger_utils import log

# Load environment variables from .env file
load_dotenv()

def get_encryption_key():
    """Get or generate encryption key"""
    key = os.getenv("ENCRYPTION_KEY", "")
    if not key:
        log("\n" + "="*60)
        log("  [SECURITY ERROR] ENCRYPTION_KEY not set!")
        log("="*60)
        log("\nRun: python init_security.py")
        log("\nThis will generate ENCRYPTION_KEY\n")
        sys.exit(1)
    
    # Key is already Fernet-compatible (generated by Fernet.generate_key())
    return key.encode()

# Initialize Fernet cipher
_cipher = None

def get_cipher():
    """Get Fernet cipher instance"""
    global _cipher
    if _cipher is None:
        _cipher = Fernet(get_encryption_key())
    return _cipher

def encrypt_password(password: str) -> str:
    """
    Encrypt password for storage
    
    Args:
        password: Plain text password
        
    Returns:
        Encrypted password (base64 string)
    """
    if not password:
        return ""
    
    cipher = get_cipher()
    encrypted = cipher.encrypt(password.encode())
    return encrypted.decode()

def decrypt_password(encrypted_password: str) -> str:
    """
    Decrypt password from storage
    
    Args:
        encrypted_password: Encrypted password string
        
    Returns:
        Plain text password
    """
    if not encrypted_password:
        return ""
    
    # Попытка расшифровать
    try:
        cipher = get_cipher()
        decrypted = cipher.decrypt(encrypted_password.encode())
        return decrypted.decode()
    except Exception:
        pass  # Первая попытка не удалась
    
    # Проверка: это plain text пароль для обратной совместимости?
    # Plain text пароль НЕ должен начинаться с "gAAAAA" (Fernet prefix)
    if encrypted_password.startswith('gAAAAA'):
        # Это явно Fernet-зашифрованные данные, но расшифровка не удалась
        log(f"[ERROR] Failed to decrypt password - corrupted or wrong key", level="ERROR")
        return ""  # Возвращаем пустую строку при ошибке
    
    # Это plain text пароль (обратная совместимость)
    log(f"[INFO] Using backward compatibility mode for server credentials")
    return encrypted_password

