"""Initial migration to v2.0 with optimizations

Revision ID: 08ce99df2c3c
Revises: 
Create Date: 2025-11-10 14:42:06.539835

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '08ce99df2c3c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_quick_commands_unique'), table_name='quick_commands')
    op.alter_column('recovery_codes', 'id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
    op.alter_column('recovery_codes', 'used',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('recovery_codes', 'created_at',
               existing_type=sa.DATETIME(),
               server_default=None,
               existing_nullable=True)
    op.create_index(op.f('ix_recovery_codes_id'), 'recovery_codes', ['id'], unique=False)
    op.drop_constraint(None, 'recovery_codes', type_='foreignkey')
    op.create_foreign_key(None, 'recovery_codes', 'users', ['user_id'], ['id'])
    op.alter_column('scheduled_command_servers', 'id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
    op.drop_index(op.f('ix_scheduled_command_servers_scheduled_command_id'), table_name='scheduled_command_servers')
    op.drop_index(op.f('ix_scheduled_command_servers_server_id'), table_name='scheduled_command_servers')
    op.create_index(op.f('ix_scheduled_command_servers_id'), 'scheduled_command_servers', ['id'], unique=False)
    op.drop_constraint(None, 'scheduled_command_servers', type_='foreignkey')
    op.drop_constraint(None, 'scheduled_command_servers', type_='foreignkey')
    op.create_foreign_key(None, 'scheduled_command_servers', 'servers', ['server_id'], ['id'])
    op.create_foreign_key(None, 'scheduled_command_servers', 'scheduled_commands', ['scheduled_command_id'], ['id'])
    op.alter_column('scheduled_commands', 'id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
    op.alter_column('scheduled_commands', 'display_time',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('scheduled_commands', 'status',
               existing_type=sa.VARCHAR(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('scheduled_commands', 'created_at',
               existing_type=sa.DATETIME(),
               server_default=None,
               nullable=True)
    op.alter_column('scheduled_commands', 'use_botname',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               nullable=True)
    op.alter_column('scheduled_commands', 'delay_between_bots',
               existing_type=sa.INTEGER(),
               server_default=None,
               nullable=True)
    op.alter_column('scheduled_commands', 'target_type',
               existing_type=sa.TEXT(),
               server_default=None,
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('scheduled_commands', 'timezone',
               existing_type=sa.TEXT(),
               server_default=None,
               type_=sa.String(),
               existing_nullable=False)
    op.drop_index(op.f('ix_scheduled_commands_status'), table_name='scheduled_commands')
    op.drop_index(op.f('ix_scheduled_commands_user_id'), table_name='scheduled_commands')
    op.create_index(op.f('ix_scheduled_commands_id'), 'scheduled_commands', ['id'], unique=False)
    op.alter_column('scheduler_settings', 'id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
    op.alter_column('scheduler_settings', 'check_interval',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('scheduler_settings', 'updated_at',
               existing_type=sa.TIMESTAMP(),
               server_default=None,
               type_=sa.DateTime(),
               existing_nullable=True)
    op.create_index(op.f('ix_scheduler_settings_id'), 'scheduler_settings', ['id'], unique=False)
    op.alter_column('servers', 'group_name',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.drop_index(op.f('idx_sql_log_command_id'), table_name='sql_command_log')
    op.drop_index(op.f('idx_sql_log_received'), table_name='sql_command_log')
    op.drop_index(op.f('idx_sql_log_server'), table_name='sql_command_log')
    op.alter_column('two_factor_attempts', 'id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
    op.alter_column('two_factor_attempts', 'attempt_time',
               existing_type=sa.DATETIME(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('two_factor_attempts', 'success',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               nullable=True)
    op.drop_index(op.f('ix_two_factor_attempts_time'), table_name='two_factor_attempts')
    op.create_index(op.f('ix_two_factor_attempts_id'), 'two_factor_attempts', ['id'], unique=False)
    op.alter_column('users', 'totp_enabled',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'totp_enabled',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('(FALSE)'),
               existing_nullable=True)
    op.drop_index(op.f('ix_two_factor_attempts_id'), table_name='two_factor_attempts')
    op.create_index(op.f('ix_two_factor_attempts_time'), 'two_factor_attempts', ['attempt_time'], unique=False)
    op.alter_column('two_factor_attempts', 'success',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('0'),
               nullable=False)
    op.alter_column('two_factor_attempts', 'attempt_time',
               existing_type=sa.DATETIME(),
               server_default=sa.text('(CURRENT_TIMESTAMP)'),
               existing_nullable=False)
    op.alter_column('two_factor_attempts', 'id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
    op.create_index(op.f('idx_sql_log_server'), 'sql_command_log', ['server_id'], unique=False)
    op.create_index(op.f('idx_sql_log_received'), 'sql_command_log', ['received_at'], unique=False)
    op.create_index(op.f('idx_sql_log_command_id'), 'sql_command_log', ['command_id'], unique=False)
    op.alter_column('servers', 'group_name',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_index(op.f('ix_scheduler_settings_id'), table_name='scheduler_settings')
    op.alter_column('scheduler_settings', 'updated_at',
               existing_type=sa.DateTime(),
               server_default=sa.text('(CURRENT_TIMESTAMP)'),
               type_=sa.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('scheduler_settings', 'check_interval',
               existing_type=sa.INTEGER(),
               server_default=sa.text('5'),
               existing_nullable=False)
    op.alter_column('scheduler_settings', 'id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
    op.drop_index(op.f('ix_scheduled_commands_id'), table_name='scheduled_commands')
    op.create_index(op.f('ix_scheduled_commands_user_id'), 'scheduled_commands', ['user_id'], unique=False)
    op.create_index(op.f('ix_scheduled_commands_status'), 'scheduled_commands', ['status'], unique=False)
    op.alter_column('scheduled_commands', 'timezone',
               existing_type=sa.String(),
               server_default=sa.text("'UTC'"),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('scheduled_commands', 'target_type',
               existing_type=sa.String(),
               server_default=sa.text("'servers'"),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('scheduled_commands', 'delay_between_bots',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               nullable=False)
    op.alter_column('scheduled_commands', 'use_botname',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('0'),
               nullable=False)
    op.alter_column('scheduled_commands', 'created_at',
               existing_type=sa.DATETIME(),
               server_default=sa.text('(CURRENT_TIMESTAMP)'),
               nullable=False)
    op.alter_column('scheduled_commands', 'status',
               existing_type=sa.VARCHAR(),
               server_default=sa.text("'pending'"),
               existing_nullable=False)
    op.alter_column('scheduled_commands', 'display_time',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('scheduled_commands', 'id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
    op.drop_constraint(None, 'scheduled_command_servers', type_='foreignkey')
    op.drop_constraint(None, 'scheduled_command_servers', type_='foreignkey')
    op.create_foreign_key(None, 'scheduled_command_servers', 'scheduled_commands', ['scheduled_command_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'scheduled_command_servers', 'servers', ['server_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_scheduled_command_servers_id'), table_name='scheduled_command_servers')
    op.create_index(op.f('ix_scheduled_command_servers_server_id'), 'scheduled_command_servers', ['server_id'], unique=False)
    op.create_index(op.f('ix_scheduled_command_servers_scheduled_command_id'), 'scheduled_command_servers', ['scheduled_command_id'], unique=False)
    op.alter_column('scheduled_command_servers', 'id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
    op.drop_constraint(None, 'recovery_codes', type_='foreignkey')
    op.create_foreign_key(None, 'recovery_codes', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_recovery_codes_id'), table_name='recovery_codes')
    op.alter_column('recovery_codes', 'created_at',
               existing_type=sa.DATETIME(),
               server_default=sa.text('(CURRENT_TIMESTAMP)'),
               existing_nullable=True)
    op.alter_column('recovery_codes', 'used',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('(FALSE)'),
               existing_nullable=True)
    op.alter_column('recovery_codes', 'id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
    op.create_index(op.f('idx_quick_commands_unique'), 'quick_commands', ['user_id', 'command', 'label'], unique=1)
    # ### end Alembic commands ###
